apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    role: locust-master
    app: locust-master
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      role: locust-master
      app: locust-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: locust-master
        app: locust-master
    spec:
      containers:
      - name: locust-master
        imagePullPolicy: Always
        image: gcr.io/my-demo-project-314117/locust-tasks:latest
        env:
          - name: LOCUST_MODE
            value: master
        ports:
          - name: loc-master-web
            containerPort: 8089
            protocol: TCP
          - name: loc-master-p1
            containerPort: 5557
            protocol: TCP
          - name: loc-master-p2
            containerPort: 5558
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: locust-master-service
  name: locust-master-service
spec:
  type: NodePort
  ports:
  - port: 5557
    targetPort: 5557
    name: locust-comm-p1
  - port: 5558
    targetPort: 5558
    name: locust-comm-p2
  - port: 8089
    targetPort: 8089
    name: locust-web-ui
  selector:
    role: locust-master
    app: locust-master

