apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    role: locust-worker
    app: locust-worker
  name: locust-worker
spec:
  replicas: 10
  selector:
    matchLabels:
      role: locust-worker
      app: locust-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: locust-worker
        app: locust-worker
    spec:
      containers:
      - image: gcr.io/my-demo-project-314117/locust-tasks:latest
        imagePullPolicy: Always
        name: locust-worker
        env:
          - name: LOCUST_MODE
            value: worker
          - name: LOCUST_MASTER
            value: locust-master-service
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
