apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-production
  namespace: default
spec:
  secretName: ssl-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: Issuer
  commonName: fslgame.danielnwang.demo.altostrat.com
  dnsNames:
  - fslgame.danielnwang.demo.altostrat.com
